### ISSUE TITLE
Move this repo to Safe2.org

### ISSUE THREAD

**Issue by mitra42** [Safe2COVIDApp/bct-server#109]
This repo is in my personal Github account now, but needs moving to Safe2's space

**Comment by mitra42** [comment]
According to https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/ it looks like @jmday needs to enable "Allow members to create repositories for this organization" at least while I am doing so. 

Next step is yours @jmday, reassign it to me when that's done.

**Comment by jmday** [comment]
I couldn't find that exact capability, but I THINK I found the way to allow it by changing the base permissions for org members. Give it a try now?

**Comment by mitra42** [comment]
It has sort of worked for me, but I can no longer push from sourcetree, which is a pain, and I can't figure out what is different in terms of permissions.  I can `git push` from the command line. 

@danaronson  - have you seen any problems ?

**Comment by jmday** [comment]
Weird, @mitra42 . If you have 2FA setup, you may need to create a personal access token (Settings, Developer Settings, Personal Access token) and use that in place of your password.

**Comment by mitra42** [comment]
I intentionally don't have 2FA setup, and it doesn't appear to be a requirement on the repo - or at least I can't find it anywhere.

**Comment by jmday** [comment]
Weird... You have owner permissions in this org now. I'm not totally sure how to troubleshoot your issue, but you should be able to fiddle with things if that helps?

**Comment by danaronson** [comment]
done
