### ISSUE TITLE
Manual contact tracing - design

### ISSUE THREAD

**Issue by mitra42** [Safe2COVIDApp/bct-server#110]
There is apparantely a design on paper for hte hooks to manual contact tracers - need to get a look at this and integrate it.

**Comment by jmday** [comment]
Drew is working on proto UX/UI, but there's no paper design yet.

**Comment by mitra42** [comment]
I need to write up my note (note to self - in black notebook)

**Comment by mitra42** [comment]
Done  and merged, separate issue has #153 Spec update
