### ISSUE TITLE
Add location visit time to scan filter 

### ISSUE THREAD

**Issue by jmday** [Safe2COVIDApp/bct-server#150]
https://github.com/Safe2COVIDApp/bct-server/blob/94787034cd72122ed6a3249c98425b4193664638/tests/test_pseudoclient.py#L170-L172

Looking for exposure events (i.e. alerts) that occurred between
location_alert.start_time >= visit.start_time - 3d && location_alert.end_time <= visit.end time

**Comment by mitra42** [comment]
Are you sure? This would mean if I arrive somewhere before the carrier and leave after they arrive but before they leave, then it would not pass this test.

**Comment by mitra42** [comment]
@jmday  - didnt hear back from you, but I think what you want is 
```
location_alert.end_time > visit.start_time - 3d. && location_alert.start_time < visit.end_time
```
That defines that their visited overlaps with our visit + 3 days before it.

**Comment by jmday** [comment]
Yes. That was what I intended! Thanks for catching my typo.

Apologies. I get so many github notices in my inbox, some of them sneak by me sometimes. Please (please please) ping me in Slack if response is important?

**Comment by mitra42** [comment]
Will do .... every now and then I cycle through all outstanding issues, and look for anything that wasn't priority that got dropped, or in this case I just got around to implementing this issue and noticed the missing response.
