### ISSUE TITLE
Hospital end points

### ISSUE THREAD

**Issue by mitra42** [Safe2COVIDApp/bct-server#56]
- [x] Add hospital endpoints based on hospital doc
- [x] Make sure "replaces" architecture works as desired.

**Comment by mitra42** [comment]
@jmday - need an update on who is working on this, any plans etc.

**Comment by jmday** [comment]
I basically shared the approach we discussed with Drew so he could start creating a prototype web portal.

The doc at:
https://docs.google.com/document/d/1ememYxKlAW2ZKUGvp6v3gJeyIrQxbpNJPsM4O7HEREs/edit#heading=h.q7z8oev466g
is probably still the best we have.

**Comment by mitra42** [comment]
After a day trying to build the hospital interactions out, I had an idea, and posted a doc for you both @jmday  and @danaronson  which substantially simplifies what we need to implement. 
It might remove the need for a web portal - so would suggest Drew holds off.

**Comment by mitra42** [comment]
First version of this is now either merged or submitted as PR, there are still sub-parts to do including #152 (healthy result); #114 Health dept demo; and #153 spec update but since they have their own Issues, I'll close this.
