### ISSUE TITLE
DOS / Scale: Responses above certain size

### ISSUE THREAD

**Issue by mitra42** [Safe2COVIDApp/bct-server#62]
If the server gets a request that generates too large a data set it should respond accordingly. 

We discussed , reducing the "now" component, (which is returned) so that the client needs to make repeated requests.

**Comment by danaronson** [comment]
Sure, I suggest that there are two ways to determine too large.

1. The client sends a max count as a parameter

1. The server gets to pick how many if it wants

In addition, the server should probably send back in the json an indication that there may be more results.

**Comment by mitra42** [comment]
We did this a week or so ago
