### ISSUE TITLE
Update "until" to be "now" and add more_data

### ISSUE THREAD

**Issue by mitra42** [Safe2COVIDApp/bct-server#94]
Were returning timestamp of last request, should be "now" if provide all data.

**Comment by mitra42** [comment]
scan_status looks good ? 

But ... it looks like on sync we still need to use `iso_time_from_seconds_since_epoch(now)` instead o `iso_time_from_seconds_since_epoch(latest_time)`

@danaronson  - do you agree?

**Comment by mitra42** [comment]
@danaronson - open question on this issue for you ....

**Comment by mitra42** [comment]
- [ ] Add to config
- [ ] Add a task to be run periodically to delete any data earlier than now-(configured days)
- [ ] figure out how to run this under cron or under whatever mechanism runs sync

**Comment by mitra42** [comment]
From call: Will leave as it is now, because a) its correct even if unneccessary and b) when we do paging it will be closer to "latest_time" than "now"

**Comment by danaronson** [comment]
#129
